### ISSUE TITLE
[QUESTION] how to keep component instance variable private?

### ISSUE THREAD

**Issue by IsaacVerm** [IsaacVerm/mad-trick-explainer#1]
This issue occurred when working on the `MagicianListComponent`. The `magicians` data imported in this component is an array of objects:

```
export const magicians = [
       { name: 'Harry Houdini', trick: 'Suspended straitjacket escape' },
       { name: 'G.O.B', trick: 'Raining pennies' },
        ...
       ];
```

The`magician-list` view shows all the available magicians. So there's some extra functionality needed to go from the `magicians` data above to the `uniqueMagicianNames` property. In the component I make this happen like this:

```
export class MagicianListComponent ... {
  magicianNames = magicians.map(magician => magician.name);
  uniqueMagicianNames = Array.from(new Set(this.magicianNames))

  constructor() {}

  ngOnInit(): void {}
}
```

What's the best way to make `magicianNames` unavailable outside of the component. It's just an intermediate variable used to make the logic more clear.

![image](https://user-images.githubusercontent.com/13694871/82667001-4ac85a00-9c37-11ea-99e1-f81b5e569fd6.png)

So better would be not to see `magicianNames` here.

**Comment by Carniatto** [comment]
just simply use the private modifier

```ts
private magicianNames = magicians.map(magician => magician.name);
```

**Comment by IsaacVerm** [comment]
The extra functionality added has been moved to the `MagiciansService` so this issue is no longer relevant.
